favicon: null
name: nandoohDesign
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.6656406240072101
  brandStrength: 0.7007245942950249
  rhythmicContrast: 0.6516232031863183
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  lightness: 0.973412791499868
typography_spectrum: 0.45411
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.7425532
analytics:
  twitter: null
  google: null
  facebook: null
